import { heading } from '../components/custom/fonts'

const ProjectsSection = () => {
  return (
      <div className='pt-6 md:pt-16 px-[7%] max-[1300px]:px-[4%]'>
          <div className={`${heading.className} text-5xl`}>ProjectSection</div>
          <div className="mt-7">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus, neque! Exercitationem totam vel nobis, eaque fuga amet. Odit non impedit alias cum expedita molestias sit laborum tempora iste asperiores blanditiis doloremque modi eos odio iusto, maxime nulla dolorum. Accusantium beatae temporibus magni vel quisquam? Culpa, debitis sit animi vero voluptatibus aspernatur sunt recusandae odio deserunt labore eos eius? Illo earum natus, dignissimos inventore beatae excepturi facilis hic quasi, provident accusantium ab. Velit a sunt quis error cumque mollitia amet voluptates corporis. Minima suscipit eum similique. Dolore repellat error vel nesciunt deleniti cumque et corrupti voluptates iusto, assumenda reiciendis, ducimus nisi iure excepturi harum itaque quibusdam ipsam dolorem ex impedit sint dicta! Temporibus impedit quod similique excepturi iste ullam dicta, asperiores assumenda magni quasi officiis nobis explicabo, facere cum quo culpa veritatis soluta. Fuga perspiciatis recusandae eius saepe aliquid nemo voluptate. Tempore eos adipisci nobis delectus perspiciatis dolorem doloremque porro vitae harum ad. Laborum nobis voluptas natus maxime labore, dicta perspiciatis aspernatur est, alias nisi aliquam libero eius voluptatibus excepturi itaque! Fugit, assumenda sunt voluptatibus corrupti quo expedita, dignissimos nostrum quidem impedit amet laborum in hic, dicta minus earum. Temporibus nobis quam consequuntur. Aut sed facere architecto officiis, possimus culpa? Cupiditate voluptatibus itaque expedita cumque minus in consequuntur unde qui deleniti eum magnam accusantium odio, dolorem iusto harum dolore, rerum ea nihil blanditiis. Odit hic aspernatur quis natus quidem, qui, magni dolorum animi adipisci veniam enim, ducimus molestias ea omnis quae totam ut tempore quod minima. Quaerat ullam pariatur provident minima, quas eaque id totam nemo, corporis atque quidem enim. Veritatis accusantium rerum, eum id soluta iure voluptas porro tempore ipsum ipsam velit illum, facere voluptatem, quas harum ipsa omnis deserunt totam aliquid sapiente ab perspiciatis? Architecto labore commodi perferendis facilis reprehenderit, est consequatur minus ab necessitatibus natus, alias non aspernatur. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis in facilis expedita dolore doloremque culpa veniam assumenda, harum earum vero tempore quam voluptatum soluta eveniet. Doloribus sit cupiditate fugit. Inventore similique porro tempore autem harum. Saepe natus assumenda asperiores necessitatibus et aspernatur officiis eos</div>
          <div id='contact' className="h-[80px] md:h-[60px]"></div>
      </div>
  )
}

export default ProjectsSection